services:
  - type: web
    plan: free
    name: PETER-PARKER-BOT
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/matrixbotz0/PETER-PARKER-BOT.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: AUTH_CHANNEL
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_URL 
        sync: false 
      - key: PICS 
        sync: false
      - key: ADMINS
        sync: false    
      - key: LOG_CHANNEL
        sync: false
    autoDeploy: false 
